baseurl = "http://icaroagostino.github.io/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  
[languages]
  [languages.en]
    title = "Ícaro Agostino"
    subtitle = "Forecasting, Simulação e Otimização"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Ícaro Agostino"
      logoHomeLink = "http://icaroagostino.github.io/blog"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/sobre"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts  "
        url = "/post"
      [[languages.en.menu.main]]
        identifier = "curriculum"
        name = " Curriculum"
        url = "/curriculum"
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "  Archive"
        url = "/archive"
